"""Private file-backed secrets. Never serialize this object into diagnostics."""

from __future__ import annotations

import re
import shlex
from dataclasses import dataclass, field
from pathlib import Path

from .config import parse_yaml
from .errors import HarnessSyncError
from .filesystem import Snapshot, snapshot
from .schema import env_name


@dataclass(frozen=True)
class SecretStore:
    _values: dict[str, str] = field(repr=False)

    @classmethod
    def from_snapshot(cls, source: Snapshot) -> SecretStore:
        if source.data is None:
            raise HarnessSyncError("Secrets file is missing; run init or create it privately")
        if source.mode is None or source.mode & 0o077:
            raise HarnessSyncError("Secrets file must have mode 0600 or stricter")
        obj = parse_yaml(source.data)
        if (
            not isinstance(obj, dict)
            or set(obj) != {"version", "keys"}
            or type(obj["version"]) is not int
            or obj["version"] != 1
            or not isinstance(obj["keys"], dict)
        ):
            raise HarnessSyncError("Invalid secrets file schema")
        values = obj["keys"]
        names = set()
        for key, value in values.items():
            if (
                not isinstance(key, str)
                or not re.fullmatch(r"[a-z][a-z0-9_-]*", key)
                or not isinstance(value, str)
                or not value
                or any(c in value for c in "\x00\r\n")
            ):
                raise HarnessSyncError("Invalid secret identifier or value")
            normalized = env_name(key)
            if normalized in names:
                raise HarnessSyncError("Secret identifiers collide after environment normalization")
            names.add(normalized)
        return cls(dict(values))

    @classmethod
    def load(cls, path: Path) -> SecretStore:
        return cls.from_snapshot(snapshot(path))

    def require(self, identifiers: set[str]) -> None:
        if identifiers - self._values.keys():
            raise HarnessSyncError("A referenced secret is missing")

    def get(self, identifier: str) -> str:
        self.require({identifier})
        return self._values[identifier]

    def scoped(self, identifiers: set[str]) -> SecretStore:
        self.require(identifiers)
        return SecretStore({key: self._values[key] for key in identifiers})

    def identifiers(self) -> list[str]:
        return sorted(self._values)

    def exports(self) -> bytes:
        lines = ["# Generated by harness-sync; contains secrets. Do not commit."]
        lines += [
            f"export {env_name(key)}={shlex.quote(self._values[key])}"
            for key in sorted(self._values)
        ]
        return ("\n".join(lines) + "\n").encode()

    def contains_secret(self, value: str) -> bool:
        return any(secret in value for secret in self._values.values())
